plot.pc.space <-
function(x,...){
	
	quartz(height=,width=9);
par(mfrow=c(5,5),mar=c(1,1,1,1));
plot(x$prco.base[,1]~x$prco.base[,1],type="n",xaxt="n",yaxt="n");
text(x=max((x$prco.base[,2]))-(max((x$prco.base[,2]))-min((x$prco.base[,2])))/2,y=max((x$prco.base[,1]))-(max((x$prco.base[,1]))-min((x$prco.base[,1])))/2,labels="PC1",cex=2,pos=4);
plot(x$prco.base[,1]~x$prco.base[,2],ylim=c(min(c(x$prco.base[,1],x$prco.new[,1])),max(c(x$prco.base[,1],x$prco.new[,1]))),xlim=c(min(c(x$prco.base[,2],x$prco.new[,2])),max(c(x$prco.base[,2],x$prco.new[,2]))));
points(x$prco.new[,1]~x$prco.new[,2],col="red")
plot(x$prco.base[,1]~x$prco.base[,3],ylim=c(min(c(x$prco.base[,1],x$prco.new[,1])),max(c(x$prco.base[,1],x$prco.new[,1]))),xlim=c(min(c(x$prco.base[,3],x$prco.new[,3])),max(c(x$prco.base[,3],x$prco.new[,3]))));
points(x$prco.new[,1]~x$prco.new[,3],col="red")
plot(x$prco.base[,1]~x$prco.base[,4],ylim=c(min(c(x$prco.base[,1],x$prco.new[,1])),max(c(x$prco.base[,1],x$prco.new[,1]))),xlim=c(min(c(x$prco.base[,4],x$prco.new[,4])),max(c(x$prco.base[,4],x$prco.new[,4]))));
points(x$prco.new[,1]~x$prco.new[,4],col="red")
plot(x$prco.base[,1]~x$prco.base[,5],ylim=c(min(c(x$prco.base[,1],x$prco.new[,1])),max(c(x$prco.base[,1],x$prco.new[,1]))),xlim=c(min(c(x$prco.base[,5],x$prco.new[,5])),max(c(x$prco.base[,5],x$prco.new[,5]))));
points(x$prco.new[,1]~x$prco.new[,5],col="red")
plot(x$prco.base[,2]~x$prco.base[,1],ylim=c(min(c(x$prco.base[,2],x$prco.new[,2])),max(c(x$prco.base[,2],x$prco.new[,2]))),xlim=c(min(c(x$prco.base[,1],x$prco.new[,1])),max(c(x$prco.base[,1],x$prco.new[,1]))));
points(x$prco.new[,2]~x$prco.new[,1],col="red")
plot(x$prco.base[,2]~x$prco.base[,2],type="n",xaxt="n",yaxt="n");
text(x=max((x$prco.base[,2]))-(max((x$prco.base[,2]))-min((x$prco.base[,2])))/2,y=max((x$prco.base[,2]))-(max((x$prco.base[,2]))-min((x$prco.base[,2])))/2,labels="PC2",cex=2,pos=4);

plot(x$prco.base[,2]~x$prco.base[,3],ylim=c(min(c(x$prco.base[,2],x$prco.new[,2])),max(c(x$prco.base[,2],x$prco.new[,2]))),xlim=c(min(c(x$prco.base[,3],x$prco.new[,3])),max(c(x$prco.base[,3],x$prco.new[,3]))));
points(x$prco.new[,2]~x$prco.new[,3],col="red")
plot(x$prco.base[,2]~x$prco.base[,4],ylim=c(min(c(x$prco.base[,2],x$prco.new[,2])),max(c(x$prco.base[,2],x$prco.new[,2]))),xlim=c(min(c(x$prco.base[,4],x$prco.new[,4])),max(c(x$prco.base[,4],x$prco.new[,4]))));
points(x$prco.new[,2]~x$prco.new[,4],col="red")
plot(x$prco.base[,2]~x$prco.base[,5],ylim=c(min(c(x$prco.base[,2],x$prco.new[,2])),max(c(x$prco.base[,2],x$prco.new[,2]))),xlim=c(min(c(x$prco.base[,5],x$prco.new[,5])),max(c(x$prco.base[,5],x$prco.new[,5]))));
points(x$prco.new[,2]~x$prco.new[,5],col="red")
plot(x$prco.base[,3]~x$prco.base[,1],ylim=c(min(c(x$prco.base[,3],x$prco.new[,3])),max(c(x$prco.base[,3],x$prco.new[,3]))),xlim=c(min(c(x$prco.base[,1],x$prco.new[,1])),max(c(x$prco.base[,1],x$prco.new[,1]))));
points(x$prco.new[,3]~x$prco.new[,1],col="red")
plot(x$prco.base[,3]~x$prco.base[,2],ylim=c(min(c(x$prco.base[,3],x$prco.new[,3])),max(c(x$prco.base[,3],x$prco.new[,3]))),xlim=c(min(c(x$prco.base[,2],x$prco.new[,2])),max(c(x$prco.base[,2],x$prco.new[,2]))));
points(x$prco.new[,3]~x$prco.new[,2],col="red")
plot(x$prco.base[,3]~x$prco.base[,3],type="n",xaxt="n",yaxt="n");
text(x=max((x$prco.base[,2]))-(max((x$prco.base[,2]))-min((x$prco.base[,2])))/2,y=max((x$prco.base[,3]))-(max((x$prco.base[,3]))-min((x$prco.base[,3])))/2,labels="PC3",cex=2,pos=4);
plot(x$prco.base[,3]~x$prco.base[,4],ylim=c(min(c(x$prco.base[,3],x$prco.new[,3])),max(c(x$prco.base[,3],x$prco.new[,3]))),xlim=c(min(c(x$prco.base[,4],x$prco.new[,4])),max(c(x$prco.base[,4],x$prco.new[,4]))));
points(x$prco.new[,3]~x$prco.new[,4],col="red")
plot(x$prco.base[,3]~x$prco.base[,5],ylim=c(min(c(x$prco.base[,3],x$prco.new[,3])),max(c(x$prco.base[,3],x$prco.new[,3]))),xlim=c(min(c(x$prco.base[,5],x$prco.new[,5])),max(c(x$prco.base[,5],x$prco.new[,5]))));
points(x$prco.new[,3]~x$prco.new[,5],col="red")
plot(x$prco.base[,4]~x$prco.base[,1],ylim=c(min(c(x$prco.base[,4],x$prco.new[,4])),max(c(x$prco.base[,4],x$prco.new[,4]))),xlim=c(min(c(x$prco.base[,1],x$prco.new[,1])),max(c(x$prco.base[,1],x$prco.new[,1]))));
points(x$prco.new[,4]~x$prco.new[,1],col="red")
plot(x$prco.base[,4]~x$prco.base[,2],ylim=c(min(c(x$prco.base[,4],x$prco.new[,4])),max(c(x$prco.base[,4],x$prco.new[,4]))),xlim=c(min(c(x$prco.base[,2],x$prco.new[,2])),max(c(x$prco.base[,2],x$prco.new[,2]))));
points(x$prco.new[,4]~x$prco.new[,2],col="red")
plot(x$prco.base[,4]~x$prco.base[,3],ylim=c(min(c(x$prco.base[,4],x$prco.new[,4])),max(c(x$prco.base[,4],x$prco.new[,4]))),xlim=c(min(c(x$prco.base[,3],x$prco.new[,3])),max(c(x$prco.base[,3],x$prco.new[,3]))));
points(x$prco.new[,4]~x$prco.new[,3],col="red")
plot(x$prco.base[,4]~x$prco.base[,4],type="n",xaxt="n",yaxt="n");
text(x=max((x$prco.base[,2]))-(max((x$prco.base[,2]))-min((x$prco.base[,2])))/2,y=max((x$prco.base[,4]))-(max((x$prco.base[,4]))-min((x$prco.base[,4])))/2,labels="PC4",cex=2,pos=4);
plot(x$prco.base[,4]~x$prco.base[,5],ylim=c(min(c(x$prco.base[,4],x$prco.new[,4])),max(c(x$prco.base[,4],x$prco.new[,4]))),xlim=c(min(c(x$prco.base[,5],x$prco.new[,5])),max(c(x$prco.base[,5],x$prco.new[,5]))));
points(x$prco.new[,4]~x$prco.new[,5],col="red")
plot(x$prco.base[,5]~x$prco.base[,1],ylim=c(min(c(x$prco.base[,5],x$prco.new[,5])),max(c(x$prco.base[,5],x$prco.new[,5]))),xlim=c(min(c(x$prco.base[,1],x$prco.new[,1])),max(c(x$prco.base[,1],x$prco.new[,1]))));
points(x$prco.new[,5]~x$prco.new[,1],col="red")
plot(x$prco.base[,5]~x$prco.base[,2],ylim=c(min(c(x$prco.base[,5],x$prco.new[,5])),max(c(x$prco.base[,5],x$prco.new[,5]))),xlim=c(min(c(x$prco.base[,2],x$prco.new[,2])),max(c(x$prco.base[,2],x$prco.new[,2]))));
points(x$prco.new[,5]~x$prco.new[,2],col="red")
plot(x$prco.base[,5]~x$prco.base[,3],ylim=c(min(c(x$prco.base[,5],x$prco.new[,5])),max(c(x$prco.base[,5],x$prco.new[,5]))),xlim=c(min(c(x$prco.base[,3],x$prco.new[,3])),max(c(x$prco.base[,3],x$prco.new[,3]))));
points(x$prco.new[,5]~x$prco.new[,3],col="red")
plot(x$prco.base[,5]~x$prco.base[,4],ylim=c(min(c(x$prco.base[,5],x$prco.new[,5])),max(c(x$prco.base[,5],x$prco.new[,5]))),xlim=c(min(c(x$prco.base[,4],x$prco.new[,4])),max(c(x$prco.base[,4],x$prco.new[,4]))));
points(x$prco.new[,5]~x$prco.new[,4],col="red")
plot(x$prco.base[,5]~x$prco.base[,5],type="n",xaxt="n",yaxt="n");
text(x=max((x$prco.base[,2]))-(max((x$prco.base[,2]))-min((x$prco.base[,2])))/2,y=max((x$prco.base[,5]))-(max((x$prco.base[,5]))-min((x$prco.base[,5])))/2,labels="PC5",cex=2,pos=4);

	
	}
